
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILED = 'VALIDATE_TOKEN_FAILED';

export const LOGOUT = 'LOGOUT';

export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';

export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID';
export const GET_ITEM_BY_ID_SUCCESS = 'GET_ITEM_BY_ID_SUCCESS';
export const GET_ITEM_BY_ID_FAILED = 'GET_ITEM_BY_ID_FAILED';

export const PLACE_BID = 'PLACE_BID';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_FAILED = 'PLACE_BID_FAILED';

export const SET_AUTO_BID = 'SET_AUTO_BID';
export const SET_AUTO_BID_SUCCESS = 'SET_AUTO_BID_SUCCESS';
export const SET_AUTO_BID_FAILED = 'SET_AUTO_BID_FAILED';